name: gescolar_dev
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.2
  animations: ^1.1.1
  responsive_framework: ^0.0.7
  flutter_bloc: ^5.0.1
  bloc: ^5.0.1
  mask_text_input_formatter: ^1.0.7
  image_picker: ^0.6.7
  image_picker_for_web: ^0.1.0
  # localstorage: ^3.0.2+5
  # webstorage: ^2.0.0
  hive: ^1.4.3
  flutter_circular_chart: ^0.1.0
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  cloud_firestore_web: ^0.1.1+2
  firebase_core_web: ^0.1.1+2
  firebase_auth_web: ^0.1.3+1
  cloud_functions: ^0.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - database/
    - database/database.txt
    - images/
    - images/logo.png
    - images/home.png
    - images/LogoHappykids.png
    - images/GoogleLogo.png
    - images/firebase-logo.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OldBookshop
      fonts:
        - asset: fonts/OldBookshop.ttf
    - family: FingerPaintRegular
      fonts:
        - asset: fonts/FingerPaintRegular.ttf
    - family: conte
      fonts:
        - asset: fonts/conte.ttf
    - family: CoalhandLuke
      fonts:
        - asset: fonts/CoalhandLuke.ttf
    - family: Cheveuxdange
      fonts:
        - asset: fonts/Cheveuxdange.ttf
    - family: ArmataRegular
      fonts:
        - asset: fonts/ArmataRegular.ttf
    - family: BungeeInlineRegular
      fonts:
        - asset: fonts/BungeeInlineRegular.ttf
    - family: CabinSketchBold
      fonts:
        - asset: fonts/CabinSketchBold.ttf
    - family: CabinSketchRegular
      fonts:
        - asset: fonts/CabinSketchRegular.ttf
    - family: FrederickatheGreatRegular
      fonts:
        - asset: fonts/FrederickatheGreatRegular.ttf
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata.ttf
    - family: LibreBarcode39
      fonts:
        - asset: fonts/LibreBarcode39.ttf
    - family: LoveYaLikeASister
      fonts:
        - asset: fonts/LoveYaLikeASister.ttf
    - family: Marvel-Bold
      fonts:
        - asset: fonts/Marvel-Bold.ttf
    - family: Marvel-BoldItalic
      fonts:
        - asset: fonts/Marvel-BoldItalic.ttf
    - family: Marvel-Italic
      fonts:
        - asset: fonts/Marvel-Italic.ttf
    - family: Marvel-Regular
      fonts:
        - asset: fonts/Marvel-Regular.ttf
    - family: Spartan
      fonts:
        - asset: fonts/Spartan.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
